/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as DetonationRouteImport } from './routes/detonation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefIndexRouteImport } from './routes/brief.index'
import { Route as DetonationCanvasRouteImport } from './routes/detonation_.canvas'
import { Route as BriefNewRouteImport } from './routes/brief.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DetonationRoute = DetonationRouteImport.update({
  id: '/detonation',
  path: '/detonation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefIndexRoute = BriefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BriefRoute,
} as any)
const DetonationCanvasRoute = DetonationCanvasRouteImport.update({
  id: '/detonation_/canvas',
  path: '/detonation/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefNewRoute = BriefNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BriefRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brief': typeof BriefRouteWithChildren
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/detonation': typeof DetonationRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/brief/new': typeof BriefNewRoute
  '/detonation/canvas': typeof DetonationCanvasRoute
  '/brief/': typeof BriefIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/detonation': typeof DetonationRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/brief/new': typeof BriefNewRoute
  '/detonation/canvas': typeof DetonationCanvasRoute
  '/brief': typeof BriefIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brief': typeof BriefRouteWithChildren
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/detonation': typeof DetonationRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/brief/new': typeof BriefNewRoute
  '/detonation_/canvas': typeof DetonationCanvasRoute
  '/brief/': typeof BriefIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brief'
    | '/complete'
    | '/dashboard'
    | '/detonation'
    | '/pipeline'
    | '/settings'
    | '/brief/new'
    | '/detonation/canvas'
    | '/brief/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/dashboard'
    | '/detonation'
    | '/pipeline'
    | '/settings'
    | '/brief/new'
    | '/detonation/canvas'
    | '/brief'
  id:
    | '__root__'
    | '/'
    | '/brief'
    | '/complete'
    | '/dashboard'
    | '/detonation'
    | '/pipeline'
    | '/settings'
    | '/brief/new'
    | '/detonation_/canvas'
    | '/brief/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefRoute: typeof BriefRouteWithChildren
  CompleteRoute: typeof CompleteRoute
  DashboardRoute: typeof DashboardRoute
  DetonationRoute: typeof DetonationRoute
  PipelineRoute: typeof PipelineRoute
  SettingsRoute: typeof SettingsRoute
  DetonationCanvasRoute: typeof DetonationCanvasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detonation': {
      id: '/detonation'
      path: '/detonation'
      fullPath: '/detonation'
      preLoaderRoute: typeof DetonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/': {
      id: '/brief/'
      path: '/'
      fullPath: '/brief/'
      preLoaderRoute: typeof BriefIndexRouteImport
      parentRoute: typeof BriefRoute
    }
    '/detonation_/canvas': {
      id: '/detonation_/canvas'
      path: '/detonation/canvas'
      fullPath: '/detonation/canvas'
      preLoaderRoute: typeof DetonationCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/new': {
      id: '/brief/new'
      path: '/new'
      fullPath: '/brief/new'
      preLoaderRoute: typeof BriefNewRouteImport
      parentRoute: typeof BriefRoute
    }
  }
}

interface BriefRouteChildren {
  BriefNewRoute: typeof BriefNewRoute
  BriefIndexRoute: typeof BriefIndexRoute
}

const BriefRouteChildren: BriefRouteChildren = {
  BriefNewRoute: BriefNewRoute,
  BriefIndexRoute: BriefIndexRoute,
}

const BriefRouteWithChildren = BriefRoute._addFileChildren(BriefRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefRoute: BriefRouteWithChildren,
  CompleteRoute: CompleteRoute,
  DashboardRoute: DashboardRoute,
  DetonationRoute: DetonationRoute,
  PipelineRoute: PipelineRoute,
  SettingsRoute: SettingsRoute,
  DetonationCanvasRoute: DetonationCanvasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
