/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KpmgRouteImport } from './routes/kpmg'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as EyRouteImport } from './routes/ey'
import { Route as DetonationRouteImport } from './routes/detonation'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as BriefingRoomRouteImport } from './routes/briefing-room'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as RepoSlugRouteImport } from './routes/$repoSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence.index'
import { Route as BriefingRoomIndexRouteImport } from './routes/briefing-room.index'
import { Route as BriefIndexRouteImport } from './routes/brief.index'
import { Route as IntelligenceNewRouteImport } from './routes/intelligence.new'
import { Route as IntelligenceIdRouteImport } from './routes/intelligence.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DetonationCanvasRouteImport } from './routes/detonation_.canvas'
import { Route as BriefingRoomIdRouteImport } from './routes/briefing-room.$id'
import { Route as BriefNewRouteImport } from './routes/brief.new'
import { Route as AdminTestsRouteImport } from './routes/admin.tests'
import { Route as AdminRepositoriesRouteImport } from './routes/admin.repositories'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as IntelligenceIdEditRouteImport } from './routes/intelligence.$id_.edit'
import { Route as AdminPreviewSlugRouteImport } from './routes/admin.preview.$slug'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiRepoViewDocumentIdRouteImport } from './routes/api/repo/view.$documentId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KpmgRoute = KpmgRouteImport.update({
  id: '/kpmg',
  path: '/kpmg',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const EyRoute = EyRouteImport.update({
  id: '/ey',
  path: '/ey',
  getParentRoute: () => rootRouteImport,
} as any)
const DetonationRoute = DetonationRouteImport.update({
  id: '/detonation',
  path: '/detonation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoomRoute = BriefingRoomRouteImport.update({
  id: '/briefing-room',
  path: '/briefing-room',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const RepoSlugRoute = RepoSlugRouteImport.update({
  id: '/$repoSlug',
  path: '/$repoSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntelligenceRoute,
} as any)
const BriefingRoomIndexRoute = BriefingRoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BriefingRoomRoute,
} as any)
const BriefIndexRoute = BriefIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BriefRoute,
} as any)
const IntelligenceNewRoute = IntelligenceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => IntelligenceRoute,
} as any)
const IntelligenceIdRoute = IntelligenceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IntelligenceRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DetonationCanvasRoute = DetonationCanvasRouteImport.update({
  id: '/detonation_/canvas',
  path: '/detonation/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoomIdRoute = BriefingRoomIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BriefingRoomRoute,
} as any)
const BriefNewRoute = BriefNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BriefRoute,
} as any)
const AdminTestsRoute = AdminTestsRouteImport.update({
  id: '/admin/tests',
  path: '/admin/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRepositoriesRoute = AdminRepositoriesRouteImport.update({
  id: '/admin/repositories',
  path: '/admin/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIdEditRoute = IntelligenceIdEditRouteImport.update({
  id: '/$id_/edit',
  path: '/$id/edit',
  getParentRoute: () => IntelligenceRoute,
} as any)
const AdminPreviewSlugRoute = AdminPreviewSlugRouteImport.update({
  id: '/admin/preview/$slug',
  path: '/admin/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRepoViewDocumentIdRoute = ApiRepoViewDocumentIdRouteImport.update({
  id: '/api/repo/view/$documentId',
  path: '/api/repo/view/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$repoSlug': typeof RepoSlugRoute
  '/brief': typeof BriefRouteWithChildren
  '/briefing-room': typeof BriefingRoomRouteWithChildren
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/detonation': typeof DetonationRoute
  '/ey': typeof EyRoute
  '/intelligence': typeof IntelligenceRouteWithChildren
  '/kpmg': typeof KpmgRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/repositories': typeof AdminRepositoriesRoute
  '/admin/tests': typeof AdminTestsRoute
  '/brief/new': typeof BriefNewRoute
  '/briefing-room/$id': typeof BriefingRoomIdRoute
  '/detonation/canvas': typeof DetonationCanvasRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/intelligence/$id': typeof IntelligenceIdRoute
  '/intelligence/new': typeof IntelligenceNewRoute
  '/brief/': typeof BriefIndexRoute
  '/briefing-room/': typeof BriefingRoomIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/intelligence/$id/edit': typeof IntelligenceIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/repo/view/$documentId': typeof ApiRepoViewDocumentIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$repoSlug': typeof RepoSlugRoute
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/detonation': typeof DetonationRoute
  '/ey': typeof EyRoute
  '/kpmg': typeof KpmgRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/repositories': typeof AdminRepositoriesRoute
  '/admin/tests': typeof AdminTestsRoute
  '/brief/new': typeof BriefNewRoute
  '/briefing-room/$id': typeof BriefingRoomIdRoute
  '/detonation/canvas': typeof DetonationCanvasRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/intelligence/$id': typeof IntelligenceIdRoute
  '/intelligence/new': typeof IntelligenceNewRoute
  '/brief': typeof BriefIndexRoute
  '/briefing-room': typeof BriefingRoomIndexRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/intelligence/$id/edit': typeof IntelligenceIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/repo/view/$documentId': typeof ApiRepoViewDocumentIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$repoSlug': typeof RepoSlugRoute
  '/brief': typeof BriefRouteWithChildren
  '/briefing-room': typeof BriefingRoomRouteWithChildren
  '/complete': typeof CompleteRoute
  '/dashboard': typeof DashboardRoute
  '/deck': typeof DeckRoute
  '/detonation': typeof DetonationRoute
  '/ey': typeof EyRoute
  '/intelligence': typeof IntelligenceRouteWithChildren
  '/kpmg': typeof KpmgRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/settings': typeof SettingsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/repositories': typeof AdminRepositoriesRoute
  '/admin/tests': typeof AdminTestsRoute
  '/brief/new': typeof BriefNewRoute
  '/briefing-room/$id': typeof BriefingRoomIdRoute
  '/detonation_/canvas': typeof DetonationCanvasRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/intelligence/$id': typeof IntelligenceIdRoute
  '/intelligence/new': typeof IntelligenceNewRoute
  '/brief/': typeof BriefIndexRoute
  '/briefing-room/': typeof BriefingRoomIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/intelligence/$id_/edit': typeof IntelligenceIdEditRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/repo/view/$documentId': typeof ApiRepoViewDocumentIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$repoSlug'
    | '/brief'
    | '/briefing-room'
    | '/complete'
    | '/dashboard'
    | '/deck'
    | '/detonation'
    | '/ey'
    | '/intelligence'
    | '/kpmg'
    | '/login'
    | '/pipeline'
    | '/settings'
    | '/unsubscribe'
    | '/admin/repositories'
    | '/admin/tests'
    | '/brief/new'
    | '/briefing-room/$id'
    | '/detonation/canvas'
    | '/email/unsubscribe'
    | '/intelligence/$id'
    | '/intelligence/new'
    | '/brief/'
    | '/briefing-room/'
    | '/intelligence/'
    | '/admin/preview/$slug'
    | '/intelligence/$id/edit'
    | '/lovable/email/suppression'
    | '/api/repo/view/$documentId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$repoSlug'
    | '/complete'
    | '/dashboard'
    | '/deck'
    | '/detonation'
    | '/ey'
    | '/kpmg'
    | '/login'
    | '/pipeline'
    | '/settings'
    | '/unsubscribe'
    | '/admin/repositories'
    | '/admin/tests'
    | '/brief/new'
    | '/briefing-room/$id'
    | '/detonation/canvas'
    | '/email/unsubscribe'
    | '/intelligence/$id'
    | '/intelligence/new'
    | '/brief'
    | '/briefing-room'
    | '/intelligence'
    | '/admin/preview/$slug'
    | '/intelligence/$id/edit'
    | '/lovable/email/suppression'
    | '/api/repo/view/$documentId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/$repoSlug'
    | '/brief'
    | '/briefing-room'
    | '/complete'
    | '/dashboard'
    | '/deck'
    | '/detonation'
    | '/ey'
    | '/intelligence'
    | '/kpmg'
    | '/login'
    | '/pipeline'
    | '/settings'
    | '/unsubscribe'
    | '/admin/repositories'
    | '/admin/tests'
    | '/brief/new'
    | '/briefing-room/$id'
    | '/detonation_/canvas'
    | '/email/unsubscribe'
    | '/intelligence/$id'
    | '/intelligence/new'
    | '/brief/'
    | '/briefing-room/'
    | '/intelligence/'
    | '/admin/preview/$slug'
    | '/intelligence/$id_/edit'
    | '/lovable/email/suppression'
    | '/api/repo/view/$documentId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RepoSlugRoute: typeof RepoSlugRoute
  BriefRoute: typeof BriefRouteWithChildren
  BriefingRoomRoute: typeof BriefingRoomRouteWithChildren
  CompleteRoute: typeof CompleteRoute
  DashboardRoute: typeof DashboardRoute
  DeckRoute: typeof DeckRoute
  DetonationRoute: typeof DetonationRoute
  EyRoute: typeof EyRoute
  IntelligenceRoute: typeof IntelligenceRouteWithChildren
  KpmgRoute: typeof KpmgRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  SettingsRoute: typeof SettingsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminRepositoriesRoute: typeof AdminRepositoriesRoute
  AdminTestsRoute: typeof AdminTestsRoute
  DetonationCanvasRoute: typeof DetonationCanvasRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  AdminPreviewSlugRoute: typeof AdminPreviewSlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiRepoViewDocumentIdRoute: typeof ApiRepoViewDocumentIdRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpmg': {
      id: '/kpmg'
      path: '/kpmg'
      fullPath: '/kpmg'
      preLoaderRoute: typeof KpmgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ey': {
      id: '/ey'
      path: '/ey'
      fullPath: '/ey'
      preLoaderRoute: typeof EyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detonation': {
      id: '/detonation'
      path: '/detonation'
      fullPath: '/detonation'
      preLoaderRoute: typeof DetonationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing-room': {
      id: '/briefing-room'
      path: '/briefing-room'
      fullPath: '/briefing-room'
      preLoaderRoute: typeof BriefingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$repoSlug': {
      id: '/$repoSlug'
      path: '/$repoSlug'
      fullPath: '/$repoSlug'
      preLoaderRoute: typeof RepoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof IntelligenceRoute
    }
    '/briefing-room/': {
      id: '/briefing-room/'
      path: '/'
      fullPath: '/briefing-room/'
      preLoaderRoute: typeof BriefingRoomIndexRouteImport
      parentRoute: typeof BriefingRoomRoute
    }
    '/brief/': {
      id: '/brief/'
      path: '/'
      fullPath: '/brief/'
      preLoaderRoute: typeof BriefIndexRouteImport
      parentRoute: typeof BriefRoute
    }
    '/intelligence/new': {
      id: '/intelligence/new'
      path: '/new'
      fullPath: '/intelligence/new'
      preLoaderRoute: typeof IntelligenceNewRouteImport
      parentRoute: typeof IntelligenceRoute
    }
    '/intelligence/$id': {
      id: '/intelligence/$id'
      path: '/$id'
      fullPath: '/intelligence/$id'
      preLoaderRoute: typeof IntelligenceIdRouteImport
      parentRoute: typeof IntelligenceRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detonation_/canvas': {
      id: '/detonation_/canvas'
      path: '/detonation/canvas'
      fullPath: '/detonation/canvas'
      preLoaderRoute: typeof DetonationCanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing-room/$id': {
      id: '/briefing-room/$id'
      path: '/$id'
      fullPath: '/briefing-room/$id'
      preLoaderRoute: typeof BriefingRoomIdRouteImport
      parentRoute: typeof BriefingRoomRoute
    }
    '/brief/new': {
      id: '/brief/new'
      path: '/new'
      fullPath: '/brief/new'
      preLoaderRoute: typeof BriefNewRouteImport
      parentRoute: typeof BriefRoute
    }
    '/admin/tests': {
      id: '/admin/tests'
      path: '/admin/tests'
      fullPath: '/admin/tests'
      preLoaderRoute: typeof AdminTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/repositories': {
      id: '/admin/repositories'
      path: '/admin/repositories'
      fullPath: '/admin/repositories'
      preLoaderRoute: typeof AdminRepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/$id_/edit': {
      id: '/intelligence/$id_/edit'
      path: '/$id/edit'
      fullPath: '/intelligence/$id/edit'
      preLoaderRoute: typeof IntelligenceIdEditRouteImport
      parentRoute: typeof IntelligenceRoute
    }
    '/admin/preview/$slug': {
      id: '/admin/preview/$slug'
      path: '/admin/preview/$slug'
      fullPath: '/admin/preview/$slug'
      preLoaderRoute: typeof AdminPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/repo/view/$documentId': {
      id: '/api/repo/view/$documentId'
      path: '/api/repo/view/$documentId'
      fullPath: '/api/repo/view/$documentId'
      preLoaderRoute: typeof ApiRepoViewDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BriefRouteChildren {
  BriefNewRoute: typeof BriefNewRoute
  BriefIndexRoute: typeof BriefIndexRoute
}

const BriefRouteChildren: BriefRouteChildren = {
  BriefNewRoute: BriefNewRoute,
  BriefIndexRoute: BriefIndexRoute,
}

const BriefRouteWithChildren = BriefRoute._addFileChildren(BriefRouteChildren)

interface BriefingRoomRouteChildren {
  BriefingRoomIdRoute: typeof BriefingRoomIdRoute
  BriefingRoomIndexRoute: typeof BriefingRoomIndexRoute
}

const BriefingRoomRouteChildren: BriefingRoomRouteChildren = {
  BriefingRoomIdRoute: BriefingRoomIdRoute,
  BriefingRoomIndexRoute: BriefingRoomIndexRoute,
}

const BriefingRoomRouteWithChildren = BriefingRoomRoute._addFileChildren(
  BriefingRoomRouteChildren,
)

interface IntelligenceRouteChildren {
  IntelligenceIdRoute: typeof IntelligenceIdRoute
  IntelligenceNewRoute: typeof IntelligenceNewRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  IntelligenceIdEditRoute: typeof IntelligenceIdEditRoute
}

const IntelligenceRouteChildren: IntelligenceRouteChildren = {
  IntelligenceIdRoute: IntelligenceIdRoute,
  IntelligenceNewRoute: IntelligenceNewRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  IntelligenceIdEditRoute: IntelligenceIdEditRoute,
}

const IntelligenceRouteWithChildren = IntelligenceRoute._addFileChildren(
  IntelligenceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RepoSlugRoute: RepoSlugRoute,
  BriefRoute: BriefRouteWithChildren,
  BriefingRoomRoute: BriefingRoomRouteWithChildren,
  CompleteRoute: CompleteRoute,
  DashboardRoute: DashboardRoute,
  DeckRoute: DeckRoute,
  DetonationRoute: DetonationRoute,
  EyRoute: EyRoute,
  IntelligenceRoute: IntelligenceRouteWithChildren,
  KpmgRoute: KpmgRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  SettingsRoute: SettingsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminRepositoriesRoute: AdminRepositoriesRoute,
  AdminTestsRoute: AdminTestsRoute,
  DetonationCanvasRoute: DetonationCanvasRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  AdminPreviewSlugRoute: AdminPreviewSlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiRepoViewDocumentIdRoute: ApiRepoViewDocumentIdRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
