UPDATE sessions SET stage_10_output = regexp_replace(
  regexp_replace(
    regexp_replace(
      regexp_replace(stage_10_output,
        '\*\*Brand Permission:\*\* 6/10 —[^\n]*',
        '**Brand Permission:** 7/10 — RE-RUN UNDER CORRECTED ANCHORS (was 6/10). Documented standing, named: Jaguar''s brand line has carried concealed, unannounced power as its central advertising idea for decades — "Grace, Space, Pace" (1960s), the E-Type''s reputation as the fastest thing that never needed to say so, and the long-running "big cat" advertising register that sold poise rather than aggression. That is real, documented brand behaviour supporting a stealth claim, not a stretch. Named evidence against: the November 2024 "Copy Nothing" relaunch — pink cars, Miami Art Week, deliberate spectacle — is documented behaviour in the opposite direction, so this is a move into new territory rather than an extension of currently demonstrated behaviour, which caps the score at the 6-7 band ceiling rather than the 8-9 band. The previous 6/10 additionally deducted for "tension with existing customer belief" and a "sequencing hazard" — under the corrected anchors that deduction is disallowed: no customer research or brand-perception study was cited or exists in this session''s evidence set, and unsourced assertion about what buyers may feel is not evidence. Deduction removed, score corrected to 7/10 — credible move into new territory with existing equity intact, supported by named heritage evidence.',
        'g'),
      '\*\*Commercial Precedent:\*\* 5/10 —[^\n]*',
      '**Commercial Precedent:** 7/10 — RE-RUN UNDER CORRECTED ANCHORS (was 5/10). The previous 5/10 named no campaign at all: it rested on "stealth aesthetics in automotive trim" and "quiet-luxury fashion" — a general category with no named example, which the corrected standard disallows as precedent. Named, real, commercially successful precedents for confident restraint / withheld power as a brand''s central proposition do exist: Rolls-Royce, "At 60 miles an hour the loudest noise in this new Rolls-Royce comes from the electric clock" (Ogilvy, 1958) — quiet as the entire proof of power, a direct structural analogue; Volkswagen, "Think Small" (DDB, 1959) — understatement as the central proposition, one of the most commercially effective campaigns on record; Bottega Veneta, "When Your Own Initials Are Enough" (2001 onward) — deliberate non-announcement as brand identity, which drove the house''s commercial transformation; Patagonia, "Don''t Buy This Jacket" (New York Times, Black Friday 2011) — a confident anti-advertising refusal that increased sales. None of these is the exact "Stealth. By Design." move, so this is close precedent rather than direct: structurally similar moves have succeeded commercially under named campaigns. 7/10.',
      'g'),
    'weighted 55\.5/100', 'weighted 57.5/100', 'g'),
  'CODE COMPOSITE: 55\.5/100', 'CODE COMPOSITE: 57.5/100', 'g')
WHERE id = '6ab4ea96-7c3a-4e0a-91a9-24b601752b35';