ALTER TABLE public.sessions
  ADD COLUMN IF NOT EXISTS stage_17_output text,
  ADD COLUMN IF NOT EXISTS stage_17_error text,
  ADD COLUMN IF NOT EXISTS stage_17_selected_territory text,
  ADD COLUMN IF NOT EXISTS stage_17b_output text,
  ADD COLUMN IF NOT EXISTS stage_17b_error text,
  ADD COLUMN IF NOT EXISTS stage_18_output text,
  ADD COLUMN IF NOT EXISTS stage_18_error text,
  ADD COLUMN IF NOT EXISTS stage_18_selected_detonation text,
  ADD COLUMN IF NOT EXISTS stage_19_output text,
  ADD COLUMN IF NOT EXISTS stage_19_error text,
  ADD COLUMN IF NOT EXISTS stage_20_output text,
  ADD COLUMN IF NOT EXISTS stage_20_error text,
  ADD COLUMN IF NOT EXISTS stage_20_approved boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS stage_21_outputs jsonb,
  ADD COLUMN IF NOT EXISTS stage_21_error text,
  ADD COLUMN IF NOT EXISTS stage_22_output text,
  ADD COLUMN IF NOT EXISTS stage_22_error text,
  ADD COLUMN IF NOT EXISTS stage_22_brand_architecture text,
  ADD COLUMN IF NOT EXISTS stage_22_distinctive_assets text;